# Generated by Django 4.2.8 on 2024-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('description', models.TextField()),
            ],
        ),
    ]
