# Generated by Django 4.2.8 on 2024-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('One', '1'), ('Twi', '2'), ('sdf', '3'), ('sdf', '4'), ('sdf', '5'), ('sfse', '6'), ('sdfsd', '7')], max_length=5),
        ),
    ]
