# Generated by Django 4.2.8 on 2024-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
