# Generated by Django 4.2.8 on 2024-03-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
