# Generated by Django 4.2.8 on 2024-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('One star', '1'), ('Two star', '2'), ('Three star', '3'), ('Four star', '4'), ('Five star', '5'), ('Six star', '6'), ('Seven star', '7')], max_length=12),
        ),
    ]
